name: WooMinecraft
main: com.plugish.woominecraft.WooMinecraft
version: 1.4.6-1.12.2-1.20.2
authors: [Jirkaach]
description: A WooCommerce Minecraft Bridge
website:  http://woominecraft.com
api-version: 1.13


commands:
  woo:
    description: Check
    usage: |
        /<command> check - check for donations.
permissions:
  woo.admin:
    default: op
    description: Allows the player (or console) to use the woo commands.